<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/marco-canas/didactica_ciencia_datos/blob/main/1_propuesta/unidad_didac/2_regresion/1_get_and_data_visualization/1_get_and_visualization_tabular_regresion/1_contextualizacion_obtencion_datos_visualizacion_tabular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

Estas son las personas del programa de administración de la seccional Bajo Cauca que dan vida al desarrollo profesional a través de su aprendizaje en liderazgo, habilidades blandas e investigación:

<img src = 'https://github.com/marco-canas/7_didactica_ciencia_datos/blob/main/propuesta/unidad_didac/5_evidences_of_learning/images/g_lideres_taller_1_regresion.jpg?raw=true'>

### [Video de apoyo a la lectura interactiva y experimental de este cuaderno](https://github.com/marco-canas/7_didactica_ciencia_datos/blob/main/propuesta/unidad_didac/2_regresion/1_get_and_data_visualization/1_get_and_visualization_tabular_regresion/1_contextualizacion_obtencion_datos_visualizacion_tabular.ipynb)

## [Vínculo al programa del curso:  ](https://github.com/marco-canas/7_didactica_ciencia_datos/blob/main/propuesta/prop_invest/cartilla/cartilla.ipynb)

# Modelo general de clase: [aula invertida](https://www3.gobiernodecanarias.org/medusa/ecoescuela/pedagotic/aprendizaje-invertido-flipped-classroom/)

## Definición y características de este modelo de Aprendizaje invertido

## ¿Qué es?  

Flipped Learning o aprendizaje invertido es un enfoque pedagógico en el que:  

* la instrucción directa se realiza fuera del aula y 
* se utiliza el tiempo de clase para llevar a cabo actividades que impliquen el desarrollo de procesos cognitivos de mayor complejidad, en las que son necesarias la ayuda y la experiencia del docente.

## ¿Para qué sirve?  

Mejora el proceso de enseñanza-aprendizaje realizando,   

* fuera del aula, actividades de aprendizaje sencillas (observar, memorizar, resumir, etc.) y, 
* en el aula, actividades más complejas (razonar, examinar, priorizar, argumentar, proponer, etc.) que requieren la interacción entre iguales y la ayuda del docente como facilitador.

<img src = 'https://github.com/marco-canas/7_didactica_ciencia_datos/blob/main/propuesta/unidad_didac/atributos_aprendizaje_invertido.png?raw=true'>

# Proceso Flipped Learning

## Fuera del Aula

### Docente:

* Diseña y planea el proceso de enseñanza-aprendizaje del aula, integrando estrategias, modelos de enseñanza y metodologías (aprendizaje basado en proyectos, aprendizaje cooperativo y colaborativo,…).  

* Diseña y planea actividades que se realizarán fuera del aula (ver vídeos, cumplimentar cuestionarios,…).  

* Selecciona e integra la tecnología en actividades de aprendizaje activo.  

* Diseña actividades de evaluación que promuevan el aprendizaje del alumnado.

### Alumnado:

* Accede, cuantas veces necesite, a las actividades facilitadas por el profesorado.
* Realiza las actividades propuestas.

## En el Aula

### Docente:

* Guía y facilita los procesos de aprendizaje, atendiendo a la diversidad.
* Retroalimenta el desempeño de los equipos/grupos y del alumnado individualmente.
* Genera espacios para la coevaluación y autoevaluación.

### Alumnado:

* Realiza las actividades (debates, exposiciones orales, informes, diario de aprendizaje, cuaderno de trabajo cooperativo,…).
* Recibe retroalimentación inmediata del profesorado y de sus compañeros y compañeras.
* Accede, si fuera necesario, a las actividades previas facilitadas por el profesorado.

## Fomento de la lectura literaria asociada a Ingeniería agropecuaria y licenciatura en Matemáticas

Me doy cuenta de que mi condicionamiento cultural me lleva a centrar la atención en lugares donde es improbable que encuentre lo que busco. Desarrollé la CNV para educar mi atención, para hacer resplandecer la luz de mi conciencia en aquellas zonas donde seguramente hallaré lo que estoy buscando. Lo que busco en la vida es compasión, una corriente que fluya entre los demás y yo, basada en un mutuo dar desde el corazón.

La compasión a la que me refiero, y que defino como un «dar desde el corazón», está expresada en la siguiente letra de una canción, escrita por mi amiga Ruth Bebermeyer:  

Jamás siento que recibo tanto  
como cuando aceptas algo de mí    
cuando comprendes la alegría que siento   
al dártelo.  
Sabes que mi ofrecimiento  
no busca que estés en deuda conmigo,  
sino vivir el amor
que siento por ti.  
Recibir con gracia  
quizá sea la mayor forma de dar.  
No puedo separar una cosa de la otra.  
Cuando tú me das algo,  
yo te doy el recibirlo. 
Cuando tomas algo de mí,
siento que soy yo quien
recibe.  
-Canción de Ruth Bebermeyer titulada 
«Given To» [Recibir](https://www.youtube.com/watch?v=bRfUGfwj69U), que forma parte del álbum Given To, 1978

## [Recomendación de la UNESCO sobre la Ciencia Abierta](https://unesdoc.unesco.org/ark:/48223/pf0000379949_spa)

## FINALIDAD Y OBJETIVOS DE LA RECOMENDACIÓN  

El objetivo de la presente Recomendación es proporcionar un marco internacional para las políticas y prácticas de la ciencia abierta que reconozca las diferencias disciplinarias y regionales en las perspectivas de la ciencia abierta, tenga en cuenta la libertad académica, los enfoques transformadores en materia de género y los desafíos específicos a los que se enfrentan los científicos y otros agentes de la ciencia abierta en diferentes países y, en particular, en los países en desarrollo, y contribuya a reducir las brechas digital, tecnológica y de conocimientos que existen entre los países y 
dentro de ellos.

2. En la presente Recomendación se expone una definición común, así como valores, principios y normas compartidos para la ciencia abierta a escala internacional, y se propone un conjunto de medidas que propicien una implantación justa y equitativa  de la ciencia abierta para todas las personas en los planos individual, institucional, nacional, regional e internacional.    

3. En este sentido, los principales objetivos y ámbitos de acción de la presente Recomendación son los siguientes:  

   i. promover una definición común de la ciencia abierta, de los beneficios y desafíos que conlleva y de los diversos medios de acceder a ella;  
   ii. crear un entorno normativo propicio para la ciencia abierta;  
   iii. invertir en infraestructuras y servicios de ciencia abierta;
   iv. invertir en recursos humanos, formación, educación, alfabetización digital y 
desarrollo de capacidades para la ciencia abierta;
   v. fomentar una cultura de la ciencia abierta y armonizar los incentivos en 
favor de la ciencia abierta;
   vi. promover enfoques innovadores para la ciencia abierta en las diferentes 
etapas del proceso científico;
   vii. promover la cooperación internacional y multipartita en el contexto de la 
ciencia abierta y con miras a reducir las brechas digital, tecnológica y de 
conocimientos.

## Predicción de precio de ventas con métodos de Machine Leaning  

Contextualización y exploración tabular de datos para modelo de regresión

<img src = 'https://qph.cf2.quoracdn.net/main-qimg-4fa6cdf9aeba5917484c64ec7412f767'>

Figura tomada de IBM (2021).

Entendimiento del problema de negocio (Business understanding): Aquí se trata de entender las necesidades de la organización y definir la pregunta a responder con los datos.  

Entendimiento de datos (Data understanding): En esta etapa, Python se puede usar para extraer los datos desde una base de datos (usando, por ejemplo, las librerías sqlite3 o mysql.connector), desde un sitio web por medio de web scraping (Requests, BeautifulSoup, Selenium, etc.), o desde una API (yfinance, INEGIpy, tweepy, etc.). Luego, puedes realizar un análisis exploratorio de los datos (usando las librerías Numpy, Pandas, Matplotlib, Seaborn, etc).

Preparación de datos (Data preparation): En este paso, los datos son limpiados y transformados usando Numpy y Pandas. El objetivo es poder imputar o descartar los datos faltantes, eliminar valores extremos o crear nuevas variables usando las variables existentes en tu dataset.

Modelado (Modeling): Ya sea que realices un análisis estadístico descriptivo (Seaborn, Scipy, etc.), desarrolles un modelo de aprendizaje automático (Scikit-learn, XGBoost, etc.), o simplemente construyas un dashboard para la visualización de tus datos ya limpios y preparados (Plotly, Dash, Streamlit); Python puede ser usado para todas y cada una de estas tareas usando las librerías apropiadas.
    Evaluación (Evaluation): La exactitud de los modelos desarrollados puede ser fácilmente evaluada con Python y sus librerías Scikit-learn o Scipy.
    Despliegue o puesta en producción (Deployment): Puedes desarrollar apps en Python para que otras personas puedan interactuar con tus modelos o dashboards usando librerías como Dash o Streamlit.

Cómo puedes ver arriba, Python y sus librerías son una herramienta fabulosa para el análisis de datos.

Referencias:
* IBM (2021). Conceptos básicos de ayuda de CRISP-DM. Conceptos básicos de ayuda de CRISP-DM

### Objetivo de aprendizaje (Enunciar, de manera corta sencilla y clara para todos los asistentes)

* Realizar la obtención y la exploración tabular de los datos asociados a la construcción de un modelo de regresión de predicción de precios de vivienda.

## Establecimiento de prerrequisitos conceptuales para alcanzar el objetivo de aprendizaje trazado.   

(Elabore una lista de preguntas al rededor de los conceptos que consideres necesarios para empezar la clase).  

1. Tener a Google Colab asociado al correo institucional de los investigadores. 
2. ¿Qué es una variable aleatoria cuantitativa continua?
3. ¿En qué consiste una tarea de construcción de un modelo de regresión?

# Para el diseño de la clase tenga en cuenta algunos problemas de aprendizaje

* Afrontar los multiples errores que arroja el proceso de codificación en la constitución de un modelo de regresión. Por ejemplo: Errores de sintaxis.  

* aprender a usar de manera natural *la notación de punto* en Python.

## Secuencia conceptual introductoria a la clase

## Ver el panorama total

Your first task is to use California census data to build a model of housing prices in the state.

Su primera tarea es utilizar los datos del censo de California para construir un modelo de precios de viviendas en el estado.

This data includes metrics such as   


* the population, 
* median income, and
* median housing price 

for each block group in California.   

Block groups are the smallest geographical unit for which the US Census Bureau publishes sample data (a block group typically has a population of 600 to 3,000 people).

Estos datos incluyen métricas como


* la población,
* ingreso medio, y
* precio medio de la vivienda

para cada grupo de bloques en California.

Los grupos de bloques son la unidad geográfica más pequeña para la que la Oficina del Censo de EE. UU. publica datos de muestra (un grupo de bloques suele tener una población de 600 a 3000 personas).

We will call them “districts” for short.

Los llamaremos “distritos” para abreviar.

Your model should learn from this data and be able to predict the median housing price in any district, given all the other metrics.

Su modelo debería aprender de estos datos y poder predecir el precio medio de la vivienda en cualquier distrito, dadas todas las demás métricas.

### TIP

Since you are a well-organized data scientist, the first thing you should do is pull out your Machine Learning project checklist.

Dado que es un científico de datos bien organizado, lo primero que debe hacer es sacar la lista de verificación de su proyecto de aprendizaje automático.

You can start with the one in Appendix B; it should work reasonably well for most Machine Learning projects, but make sure to adapt it to your needs.

Puede comenzar con el del Apéndice B; debería funcionar razonablemente bien para la mayoría de los proyectos de Machine Learning, pero asegúrese de adaptarlo a sus necesidades.

## Appendix B. Machine Learning Project Checklist  (Página 968 del PDF de Geron)

This checklist can guide you through your Machine Learning projects.
There are eight main steps:
1. Frame the problem and look at the big picture.
2. Get the data.
3. Explore the data to gain insights.
4. Prepare the data to better expose the underlying data patterns to
Machine Learning algorithms.
5. Explore many different models and shortlist the best ones.
6. Fine-tune your models and combine them into a great solution.
7. Present your solution.
8. Launch, monitor, and maintain your system.
Obviously, you should feel free to adapt this checklist to your needs.

In this chapter we will go through many checklist items, but we will also skip a few, either because they are self-explanatory or because they will be discussed in later chapters.

En este capítulo revisaremos muchos elementos de la lista de verificación, pero también omitiremos algunos, ya sea porque se explican por sí mismos o porque se discutirán en capítulos posteriores.

# Frame the Problem

The first question to ask your boss is what exactly the business objective is.

Building a model is probably not the end goal. How does the company expect to use and benefit from this model?

Knowing the objective is important because it will determine how you frame the problem, which algorithms you will select, which performance measure you will use to evaluate your model, and how much effort you will spend tweaking it.

Conocer el objetivo es importante porque determinará:
* cómo enmarcará el problema, 
* qué algoritmos seleccionará, 
* qué medida de rendimiento utilizará para evaluar su modelo y 
* cuánto esfuerzo dedicará a ajustarlo.

Your boss answers that your model’s output (a prediction of a district’s median housing price) will be fed to another Machine Learning system (see Figure 2-2), along with many other signals.

Su jefe responde que el resultado de su modelo (una predicción del precio medio de la vivienda de un distrito) se enviará a otro sistema de aprendizaje automático (consulte la Figura 2-2), junto con muchas otras señales.

This downstream system will determine whether it is worth investing in a given area or not. Getting this right is critical,
as it directly affects revenue.

Este sistema aguas abajo determinará si vale la pena invertir en un área determinada o no. Hacer esto bien es fundamental,
ya que afecta directamente los ingresos.


<img src = 'https://github.com/marco-canas/7_didactica_ciencia_datos/blob/main/propuesta/unidad_didac/2_regresion/5_imagenes/fig_2_2.png?raw=true'>

## PIPELINES

A sequence of data processing components is called a data pipeline.

Una secuencia de componentes de procesamiento de datos se denomina canalización de datos.

Pipelines are very common in Machine Learning systems, since there is a lot of data to manipulate and many data transformations to apply.

Las canalizaciones son muy comunes en los sistemas de aprendizaje automático, ya que hay una gran cantidad de datos para manipular y muchas transformaciones de datos para aplicar.

Components typically run asynchronously. Each component pulls in a large amount of data, processes it, and spits out the result in another data store.

Then, some time later, the next component in the pipeline pulls this data and spits out its own output. Each component is fairly self-contained: the interface between components is simply the data store.

This makes the system simple to grasp (with the help of a data flow graph), and different teams can focus on different components.

Moreover, if a component breaks down, the downstream components can often continue to run normally (at
least for a while) by just using the last output from the broken component.

This makes the architecture quite robust.

On the other hand, a broken component can go unnoticed for some time if proper monitoring is not implemented.

The data gets stale and the overall system’s performance drops.

The next question to ask your boss is what the current solution looks like (if any).

The current situation will often give you a reference for performance, as well as insights on how to solve the problem.

Your boss answers that the district housing prices are currently estimated manually by experts: a team gathers up to-date information about a district, and when they cannot get the median housing price, they estimate it using complex rules.

This is costly and time-consuming, and their estimates are not great; in cases where they manage to find out the actual median housing price, they often realize that their estimates were off by more than 20%.

This is why the company thinks that it would be useful to train a model to predict a district’s
median housing price, given other data about that district.

The census data looks like a great dataset to exploit for this purpose, since it includes the median
housing prices of thousands of districts, as well as other data.

With all this information, you are now ready to start designing your system.

First, you need to frame the problem: is it supervised, unsupervised, or Reinforcement Learning?

Is it a classification task, a regression task, or something else?

Should you use batch learning or online learning techniques?

Before you read on, pause and try to answer these questions for yourself.

Have you found the answers?

Let’s see: it is clearly a typical supervised learning task, since you are given labeled training examples (each instance comes with the expected output, i.e., the district’s median housing price).

It is also a typical regression task, since you are asked to predict a value.

More specifically, this is a multiple regression problem, since the system will use multiple features to make a prediction (it will use the district’s population, the median income, etc.).

It is also a univariate regression problem, since we are only trying to predict a single value for each district.

If we were trying to predict multiple values per district, it would be a multivariate regression
problem.

Finally, there is no continuous flow of data coming into the system, there is no particular need to adjust to changing data rapidly, and the data is small enough to fit in memory, so plain batch learning should do just fine.

### TIP
If the data were huge, you could either split your batch learning work across multiple servers
(using the MapReduce technique) or use an online learning technique.

# Select a Performance Measure

Your next step is to select a performance measure.

A typical performance measure for regression problems is the Root Mean Square Error (RMSE).

It gives an idea of how much error the system typically makes in its predictions, with a higher weight for large errors.

Equation 2-1 shows the mathematical formula to compute the RMSE.  

Equation 2-1. Root Mean Square Error (RMSE)  

$$ RMSE(X,h) =  \sqrt{ \frac{1}{m} \sum_{i = 1}^{m} (h(x_{i}) - y_{i})^{2} } $$

Even though the RMSE is generally the preferred performance measure for regression tasks, in some contexts you may prefer to use another function.

For example, suppose that there are many outlier districts. In that case, you may consider using the mean absolute error (MAE, also called the average absolute deviation; see Equation 2-2):  

#### Equation 2-2. Mean absolute error (MAE)

$$ MAE(X,h) =  \frac{1}{m} \sum_{i = 1}^{m} | h(x_{i}) - y_{i} | $$

Both the RMSE and the MAE are ways to measure the distance between two vectors: the vector of predictions and the vector of target values. Various distance measures, or norms, are possible:  

Computing the root of a sum of squares (RMSE) corresponds to the Euclidean norm: this is the notion of distance you are familiar with.

It is also called the $\mathcal{l}$ norm, noted $\Vert \cdot \Vert$ (or just $\Vert \cdot \Vert$).

Computing the sum of absolutes (MAE) corresponds to the $\mathcal{l}$ norm, noted ∥ · ∥ .

This is sometimes called the Manhattan norm because it measures the distance between two points in a city if you can only
travel along orthogonal city blocks.

More generally, the ℓ norm of a vector v containing n elements is
defined as 

$$ ∥v∥k = (|v0| k + |v1| k + ⋯ + |vn| k) 1 k .$$

ℓ gives the number of nonzero elements in the vector, and ℓ gives the maximum absolute value in the vector.

The higher the norm index, the more it focuses on large values and neglects small ones.

This is why the RMSE is more sensitive to outliers than the MAE.

But when outliers are exponentially rare (like in a bell-shaped curve), the RMSE performs very well and is generally
preferred.

# Check the Assumptions

Lastly, it is good practice to list and verify the assumptions that have been made so far (by you or others); this can help you catch serious issues early on.

For example, the district prices that your system outputs are going to be fed into a downstream Machine Learning system, and you assume that these prices are going to be used as such.

But what if the downstream system converts the prices into categories (e.g., “cheap,” “medium,” or “expensive”) and then uses those categories instead of the prices themselves?

In this case, getting the price perfectly right is not important at all; your system just needs to get the category right.

If that’s so, then the problem should have been framed as a classification task, not a regression task. You don’t want to find this out after working on a regression system for months.

Si es así, entonces el problema debería haberse planteado como una tarea de clasificación, no como una tarea de regresión. No querrá descubrir esto después de trabajar en un sistema de regresión durante meses.

# Obtención de datos


It’s time to get your hands dirty. Don’t hesitate to pick up your laptop and walk through the following code examples in a Jupyter notebook.

The full Jupyter notebook is available at https://github.com/ageron/handson-ml2.

# [Download the Data](https://github.com/ageron/handson-ml3/blob/main/02_end_to_end_machine_learning_project.ipynb)

In typical environments your data would be available in a relational database (or some other common data store) and spread across multiple tables/documents/files.

To access it, you would first need to get your credentials and access authorizations and familiarize yourself with the data schema.

In this project, however, things are much simpler: you will just download a single compressed file, housing.tgz, which contains a comma-separated values (CSV) file called housing.csv with all the data.

You could use your web browser to download the file and run tar xzf housing.tgz to decompress it and extract the `.CSV` file, but it is preferable to create a small function to do that.

Puede usar su navegador web para descargar el archivo y ejecutar tar xzf housing.tgz para descomprimirlo y extraer el archivo `.CSV`, pero es preferible crear una pequeña función para hacerlo.

Having a function that downloads the data is useful in particular if the data changes regularly: you can write a small script that uses the function to fetch the latest data (or you can set up a scheduled job to do that automatically at regular intervals).

Tener una función que descargue los datos es útil en particular si los datos cambian regularmente: puede escribir un pequeño script que use la función para obtener los datos más recientes (o puede configurar un trabajo programado para hacerlo automáticamente a intervalos regulares).

Automating the process of fetching the data is also useful if you need to install the dataset on multiple machines.

Automatizar el proceso de obtención de datos también es útil si necesita instalar el conjunto de datos en varias máquinas.

Here is the function to fetch the data:

In [2]:
from pathlib import Path
import pandas as pd
import tarfile
import urllib.request

def load_housing_data():
    tarball_path = Path("datasets/housing.tgz") 
    if not tarball_path.is_file():
        Path("datasets").mkdir(parents=True, exist_ok=True)
        url = "https://github.com/ageron/data/raw/main/housing.tgz"
        urllib.request.urlretrieve(url, tarball_path)
        with tarfile.open(tarball_path) as housing_tarball:
            housing_tarball.extractall(path="datasets")
    return pd.read_csv(Path("datasets/housing/housing.csv"))

In [3]:
housing = load_housing_data()

This function returns a pandas DataFrame object containing all the data.

# Take a Quick Look at the Data Structure

Let’s take a look at the top five rows using the DataFrame’s `head()` method (see Figure 2-5).

Echemos un vistazo a las cinco filas superiores usando el método `head()` de DataFrame (vea la Figura 2-5).

In [4]:
housing.head() # Ver encabezado de los datos como DataFrame

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [5]:
housing.tail() # mostrar la cola o finalización del dataset

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

Each row represents one district. There are 10 attributes (you can see the first 6 in the screenshot): longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, `households`, median_income, median_house_value, and `ocean_proximity`.  

The `.info()` method is useful to get a quick description of the data, in particular the total number of rows, each attribute’s type, and the number of nonnull values (see Figure 2-6).

In [6]:
housing.info() # ver lista de atributos y determinar la naturaleza de las variables aleatorias asocuadas al problema

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

## Mapa conceptual de la clase elaborado en CMapTools

<img src = 'https://github.com/marco-canas/7_didactica_ciencia_datos/blob/main/propuesta/unidad_didac/2_regresion/5_imagenes/contextualizaci%C3%B3n,%20obtenci%C3%B3n%20y%20visualizaci%C3%B3n%20tabular%20de%20datos%20-%20%C2%BFC%C3%B3mo%20obtener%20los%20datos.jpg?raw=true'>

## Tareas para realizar antes de la clase

1. Ver los videos respectivos []()
2. Memorizar las definiciones [variable cuantitativa contunua](https://voca.ro/1iNBBDDOJy8m)
3. Sintetizar o resumir la información en mapas conceptuales. []()

# Tareas para realizar en clase

* Modelación matemática 
* Trabajo en equipos

# Tareas para realizar después de la realización de la clase

* Actividades de memorización: 
  - escucha reiterada de grabaciones de formulas y resultados científicos. 
  - relectura de notas. 
  - ejercicios de mayor complejidad.

# Primera tarea de memorización de un procedimiento de obtención de datos, creación de DataFrame y visualización del mismo

1. Importe la librería pandas con el seudónimo de su preferencia 

2. Cree una variable que contenga la dirección donde están alojados los datos. 
3. llamar a la función `read_csv()` o `read_excel()` y evaluarla en la url anterior para obtener los datos como dataframe.

4. guarde ese dataframe en una variable llamada `datos_meteorologicos_caucasia`

## Ejemplo ilustrativo de solución de esta tarea

In [7]:
import pandas as pd 
url = "https://raw.githubusercontent.com/marco-canas/7_didactica_ciencia_datos/main/datasets/antioquia_mira_su_cielo/A2022M11/DatosEstacion2022-11-17.csv"

datos_meteorologicos_caucasia = pd.read_csv(url)

In [8]:
datos_meteorologicos_caucasia

,Tiempo Sistema,Bar Trend,Next Record,Barometer,Inside Temperature,Inside Humidity,Outside Temperature,Wind Speed,10 Min Avg Wind Speed,Wind Direction,...,Soil & Leaf Alarms,Transmitter Battery Status,Console Battery Voltage,Forecast Icons,Forecast Rule number,Time of Sunrise,Time of Sunset,<LF> = 0x0A,<CR> = 0x0D,CRC
0,2022-11-17 00:00:00,O,662,29819,849,77,770,0,0,313,...,0,0,771,6,45,553,1738,10,13,6794
1,2022-11-17 00:01:00,O,663,29818,849,77,770,1,0,64,...,0,0,771,6,45,553,1738,10,13,8858
2,2022-11-17 00:02:00,O,663,29822,849,77,770,0,0,64,...,0,0,771,6,45,553,1738,10,13,60562
3,2022-11-17 00:03:00,O,663,29820,849,77,770,0,0,64,...,0,0,771,6,45,553,1738,10,13,58729
4,2022-11-17 00:04:01,O,663,29821,849,77,770,0,0,64,...,0,0,771,6,45,553,1738,10,13,29084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1432,2022-11-17 23:55:00,O,707,29828,867,75,770,1,3,306,...,0,0,770,6,45,554,1739,10,13,743
1433,2022-11-17 23:56:06,O,707,29830,867,75,770,1,3,297,...,0,0,770,6,45,554,1739,10,13,55640
1434,2022-11-17 23:57:00,O,707,29830,867,75,770,2,3,318,...,0,0,770,6,45,554,1739,10,13,21455
1435,2022-11-17 23:58:00,O,707,29830,866,75,770,1,2,296,...,0,0,770,6,45,554,1739,10,13,39374
1436,2022-11-17 23:59:01,O,707,29829,866,75,770,1,2,290,...,0,0,770,6,45,554,1739,10,13,17736

In [12]:
datos_meteorologicos_caucasia.head() # cómo ver el encabezado de estos datos

,Tiempo Sistema,Bar Trend,Next Record,Barometer,Inside Temperature,Inside Humidity,Outside Temperature,Wind Speed,10 Min Avg Wind Speed,Wind Direction,...,Soil & Leaf Alarms,Transmitter Battery Status,Console Battery Voltage,Forecast Icons,Forecast Rule number,Time of Sunrise,Time of Sunset,<LF> = 0x0A,<CR> = 0x0D,CRC
0,2022-11-17 00:00:00,O,662,29819,849,77,770,0,0,313,...,0,0,771,6,45,553,1738,10,13,6794
1,2022-11-17 00:01:00,O,663,29818,849,77,770,1,0,64,...,0,0,771,6,45,553,1738,10,13,8858
2,2022-11-17 00:02:00,O,663,29822,849,77,770,0,0,64,...,0,0,771,6,45,553,1738,10,13,60562
3,2022-11-17 00:03:00,O,663,29820,849,77,770,0,0,64,...,0,0,771,6,45,553,1738,10,13,58729
4,2022-11-17 00:04:01,O,663,29821,849,77,770,0,0,64,...,0,0,771,6,45,553,1738,10,13,29084

In [13]:
datos_meteorologicos_caucasia.tail() # observar las cinco últimas instancias de los datos

,Tiempo Sistema,Bar Trend,Next Record,Barometer,Inside Temperature,Inside Humidity,Outside Temperature,Wind Speed,10 Min Avg Wind Speed,Wind Direction,...,Soil & Leaf Alarms,Transmitter Battery Status,Console Battery Voltage,Forecast Icons,Forecast Rule number,Time of Sunrise,Time of Sunset,<LF> = 0x0A,<CR> = 0x0D,CRC
1432,2022-11-17 23:55:00,O,707,29828,867,75,770,1,3,306,...,0,0,770,6,45,554,1739,10,13,743
1433,2022-11-17 23:56:06,O,707,29830,867,75,770,1,3,297,...,0,0,770,6,45,554,1739,10,13,55640
1434,2022-11-17 23:57:00,O,707,29830,867,75,770,2,3,318,...,0,0,770,6,45,554,1739,10,13,21455
1435,2022-11-17 23:58:00,O,707,29830,866,75,770,1,2,296,...,0,0,770,6,45,554,1739,10,13,39374
1436,2022-11-17 23:59:01,O,707,29829,866,75,770,1,2,290,...,0,0,770,6,45,554,1739,10,13,17736

In [9]:
datos_meteorologicos_caucasia.shape # ver la forma general del dataset, es decir, ver cuentas filas y cuentas columnas componen al dataset

(1437, 42)

In [ ]:
datos_meteorologicos_caucasia.keys() # cuales atributos

Index(['Tiempo Sistema', 'Bar Trend', 'Next Record', 'Barometer',
       'Inside Temperature', 'Inside Humidity', 'Outside Temperature',
       'Wind Speed', '10 Min Avg Wind Speed', 'Wind Direction',
       'Extra Temperatures', 'Soil Temperatures', 'Leaf Temperatures',
       'Outside Humidity', 'Extra Humidties', 'Rain Rate', 'UV',
       'Solar Radiation', 'Storm Rain', 'Start Date of current Storm',
       'Day Rain', 'Month Rain', 'Year Rain', 'Day ET', 'Month ET', 'Year ET',
       'Soil Moistures', 'Leaf Wetnesses', 'Inside Alarms', 'Rain Alarms',
       'Outside Alarms', 'Extra Temp/Hum Alarms', 'Soil & Leaf Alarms',
       'Transmitter Battery Status', 'Console Battery Voltage',
       'Forecast Icons', 'Forecast Rule number', 'Time of Sunrise',
       'Time of Sunset', '<LF> = 0x0A', '<CR> = 0x0D', 'CRC'],
      dtype='object')

In [17]:
len(datos_meteorologicos_caucasia.keys() ) # cuantos atributos hay en el dataset

42

In [10]:
datos_meteorologicos_caucasia.info() # ver la lista vertical de los atributos y ver la naturaleza de las variables aleatorias que componen el dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1437 entries, 0 to 1436
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Tiempo Sistema               1437 non-null   object
 1   Bar Trend                    1437 non-null   object
 2   Next Record                  1437 non-null   int64
 3   Barometer                    1437 non-null   int64
 4   Inside Temperature           1437 non-null   int64
 5   Inside Humidity              1437 non-null   int64
 6   Outside Temperature          1437 non-null   int64
 7   Wind Speed                   1437 non-null   int64
 8   10 Min Avg Wind Speed        1437 non-null   int64
 9   Wind Direction               1437 non-null   int64
 10  Extra Temperatures           1437 non-null   int64
 11  Soil Temperatures            1437 non-null   int64
 12  Leaf Temperatures            1437 non-null   int64
 13  Outside Humidity             1437 non-null   int64
 14  Extra Humidties              1437 non-null   int64
 15  Rain Rate                    1437 non-null   int64
 16  UV                           1437 non-null   int64
 17  Solar Radiation              1437 non-null   int64
 18  Storm Rain                   1437 non-null   int64
 19  Start Date of current Storm  1437 non-null   int64
 20  Day Rain                     1437 non-null   int64
 21  Month Rain                   1437 non-null   int64
 22  Year Rain                    1437 non-null   int64
 23  Day ET                       1437 non-null   int64
 24  Month ET                     1437 non-null   int64
 25  Year ET                      1437 non-null   int64
 26  Soil Moistures               1437 non-null   int64
 27  Leaf Wetnesses               1437 non-null   int64
 28  Inside Alarms                1437 non-null   int64
 29  Rain Alarms                  1437 non-null   int64
 30  Outside Alarms               1437 non-null   int64
 31  Extra Temp/Hum Alarms        1437 non-null   int64
 32  Soil & Leaf Alarms           1437 non-null   int64
 33  Transmitter Battery Status   1437 non-null   int64
 34  Console Battery Voltage      1437 non-null   int64
 35  Forecast Icons               1437 non-null   int64
 36  Forecast Rule number         1437 non-null   int64
 37  Time of Sunrise              1437 non-null   int64
 38  Time of Sunset               1437 non-null   int64
 39  <LF> = 0x0A                  1437 non-null   int64
 40  <CR> = 0x0D                  1437 non-null   int64
 41  CRC                          1437 non-null   int64
dtypes: int64(40), object(2)
memory usage: 471.6+ KB

In [21]:
type(datos_meteorologicos_caucasia['Tiempo Sistema'][0])

str

In [11]:
datos_meteorologicos_caucasia.describe() # sintesis de los datos numéricos

,Next Record,Barometer,Inside Temperature,Inside Humidity,Outside Temperature,Wind Speed,10 Min Avg Wind Speed,Wind Direction,Extra Temperatures,Soil Temperatures,...,Soil & Leaf Alarms,Transmitter Battery Status,Console Battery Voltage,Forecast Icons,Forecast Rule number,Time of Sunrise,Time of Sunset,<LF> = 0x0A,<CR> = 0x0D,CRC
count,1437.00000,1437.000000,1437.000000,1437.000000,1437.000000,1437.000000,1437.000000,1437.000000,1437.0,1437.0,...,1437.0,1437.0,1437.000000,1437.000000,1437.000000,1437.000000,1437.000000,1437.0,1437.0,1437.000000
mean,685.64231,29793.480863,872.371608,73.158664,835.579680,1.688239,2.978427,198.145442,65535.0,65535.0,...,0.0,0.0,769.983299,5.070981,118.013918,553.250522,1738.957550,10.0,13.0,33028.402923
std,12.87702,49.931811,31.411187,5.996275,844.473711,6.890020,18.911506,866.497995,0.0,0.0,...,0.0,0.0,1.852800,1.767621,60.820903,0.433464,0.201683,0.0,0.0,18826.811535
min,662.00000,29689.000000,825.000000,59.000000,764.000000,0.000000,0.000000,5.000000,65535.0,65535.0,...,0.0,0.0,763.000000,0.000000,45.000000,553.000000,1738.000000,10.0,13.0,20.000000
25%,674.00000,29765.000000,843.000000,68.000000,770.000000,0.000000,0.000000,86.000000,65535.0,65535.0,...,0.0,0.0,768.000000,3.000000,45.000000,553.000000,1739.000000,10.0,13.0,16599.000000
50%,686.00000,29803.000000,872.000000,73.000000,775.000000,1.000000,1.000000,163.000000,65535.0,65535.0,...,0.0,0.0,770.000000,6.000000,75.000000,553.000000,1739.000000,10.0,13.0,33723.000000
75%,696.00000,29836.000000,900.000000,78.000000,873.000000,2.000000,3.000000,277.000000,65535.0,65535.0,...,0.0,0.0,772.000000,6.000000,172.000000,554.000000,1739.000000,10.0,13.0,49118.000000
max,707.00000,29866.000000,929.000000,83.000000,32767.000000,255.000000,255.000000,32767.000000,65535.0,65535.0,...,0.0,0.0,772.000000,7.000000,193.000000,554.000000,1739.000000,10.0,13.0,65494.000000

# otras acciones para desarrollar la habilidad de obtención, y visualización de los datos.

La tarea será convertir en dataframe cada uno de los csv file del dadaset de Antioquia mira su cielo. 

El enlace para es repositorio es:  https://github.com/marco-canas/7_didactica_ciencia_datos/tree/main/datasets/antioquia_mira_su_cielo

* Diga cuantas variables meteorológicas contiene cada dataset
* Cada cuántos minutos toma datos la estación. (para ello utilice el atributo `.shape`)
* compare las ventajas de pandas frente a excel para explorar el dataset.
* cuáles atributos o variables están consignadas en el dataset (utilice el método .keys())
* liste verticalmente las variables del dataset (utilice la par ello en método `.info()`)
* cuántos atributos mide (utilice la función `len()`)
* tome el atributo de tiempo real e ingrese al almenos uno de essos datos para que correbore de que eswta es una variable categórica. 
 
* Cómo se identifica que es categórica a través de el método info(). 
* Calcule el promedio de todos los atributos numéricos. (para eso utilice el método .describe()). 
* Determine con el método describe la variabilidad de los datos.

## Estrategias propuestas para la solución de las dificultades de aprendizaje detectadas

* Utilizar la red social [stackoverflow](https://stackoverflow.com/)

## Cuestionario para realizar labores de memorización, observación,  y síntesis de la información

1.

## Grabaciones en audio para fomentar la capacidad de memorizar enunciados de teoremas y resultados científicos y la capacidad de parafrasear estos resultados.

Se dispondrá de un lugar en el OneDrive asociado al correo institucional de la Universidad Antioquia del Profesor Marco Cañas, para albergar los archivos de audio de fomento a la memorización, enunciación y parafraseo de los resultados científicos, propiedades, reglas, etc. 

* [Vocaroo](https://vocaroo.com/)

### Comparta sus cuadernos y videos, evidencias de su aprendizaje [aquí](https://forms.office.com/Pages/ResponsePage.aspx?id=IefhmYRxjkmK_7KtTlPBwkanXIs1i1FEujpsZgO6dXpUMEMwTEZVMzEwVVBPTElWNVg5OVEyWUhMUy4u)

# Vocabulary for datascience

1. rows: filas
2. columns: columnas.  
3. head: cabeza. (para mostrar el inicio de los datos)
4. tail: cola.  (para ver la parte final de los datos)
5. shape: forma (cuantas filas y cuantas columnas)
6. size: tañano (filas por columnas)
7. keys: llaves (nombres de las variables incluidas en el datasets)  
8. string: cadena (mensajes verbales no numéricos)
9. type: tipo (tipo de dato) 
10. describe: describir (para sistetizar los datos numéricos)
11. standard: estandar (std es para la desviación entandar o promedio de variablidad de los datos. )

## Quiz de 5 minutos para ejercitación y adquisición de habilidades

## Referentes

* [stewart precálculo](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ERHIq62I6qFNrmxy6LZb8ZMBci7kUsyNME1nIh9yCBMJ_w?e=0zMSla)  

* [stewart cálculo](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/EZgXZjAp8QxPqOAim2hs6LcBNPLGjSHf-xwYnUVYkwa04w?e=RZdTCy)  

* [larson](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ES71ChFeO9ZDhW3TwC5Ijk8BjxUK3Pdqz_fjHxTTFAfIAg?e=VDEjfu)

* [uzcategui](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ETDikm-lVl1Or8XoEo9oyh0BEti9Zs8le-f0D-dBdtZmbA?e=bBsoyQ)

* [Cálculo de Purcell](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ES60UB4h-QFFqqRQUFmkpWcBIgoLBJeqTfZjNajWNWSeJA?e=9NxjKJ)

* [Recomendación de la UNESCO sobre ciencia abierta](https://unesdoc.unesco.org/ark:/48223/pf0000379949_spa)  

* [Geron, Aurelien. End to end. GitHub](https://github.com/ageron/handson-ml3/blob/main/02_end_to_end_machine_learning_project.ipynb)

* [tutorial de python](https://docs.python.org/es/3/tutorial/)  

* [Metodología CRIS-DM para minería de datos](https://www.ibm.com/docs/es/spss-modeler/saas?topic=dm-crisp-help-overview)

* [stackoverflow](https://stackoverflow.com/questions/59813807/understanding-invalid-decimal-literal) para gestionar errores de codificación en la constitución de modelos de machine learning con python

### [Evaluamos al profesor Marco Cañas Aquí](https://forms.office.com/Pages/ResponsePage.aspx?id=IefhmYRxjkmK_7KtTlPBwkanXIs1i1FEujpsZgO6dXpUREJPV1kxUk1JV1ozTFJIQVNIQjY5WEY3US4u)

## [Evaluación luego de alcanzar estos objetivos de aprendizaje]()

### Continue su aprendizaje en la siguiente clase a través del siguiente [vínculo](https://github.com/marco-canas/7_didactica_ciencia_datos/blob/main/propuesta/unidad_didac/2_regresion/1_get_and_data_visualization/2_visualizacion_grafica_regresion/1_visualizacion_grafica_datos_regresion.ipynb)

# Conjeturas pedagógicas fruto de la aplicación del modelo de aprendizaje invertido y del enfoque hacia la ciencia de datos con python

1. Todo cálculo o resultado debe ser interpretado en una línea markdown del cuaderno Jupyter, inmediatamente después de la enunciación del resultado y después de la presentación de una tabla o gráfico bidimensional, de tal menera que el estudiante explicite la comprensión verbal del resultado y las inferencias o estrategias que este resultado le sugieren.

## Agradecimientos  

Doy gracias a Dios por la vida de mi Hijo Joseph Cañas Osorio y la madurez que ha alcanzado.

Y a mi esposa Yasmira por su apoyo, orientación y acompañamiento.