In [2]:
import pandas as pd

In [3]:
v = pd.read_csv('https://raw.githubusercontent.com/marco-canas/didactica_ciencia_datos/main/datasets/vivienda/vivienda.csv')

In [3]:
v

,longitud,latitud,antiguedad,habitaciones,dormitorios,población,hogares,ingresos,proximidad,precio
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY,342200.0
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND,78100.0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND,77100.0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND,92300.0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND,84700.0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND,89400.0

In [1]:
from c_2 import dividir_entrenamiento_testeo

In [6]:
train_set, test_set = dividir_entrenamiento_testeo(v, 0.2)

# Visualización tyabular de los datos

In [7]:
train_set

,longitud,latitud,antiguedad,habitaciones,dormitorios,población,hogares,ingresos,proximidad,precio
2975,-119.08,35.32,8.0,11609.0,2141.0,5696.0,2100.0,5.0012,INLAND,106300.0
7448,-118.18,33.95,39.0,2121.0,579.0,1991.0,528.0,2.9094,<1H OCEAN,152200.0
3499,-118.45,34.27,35.0,1579.0,300.0,1012.0,265.0,5.1296,<1H OCEAN,195900.0
4990,-118.31,33.99,48.0,2235.0,433.0,1363.0,433.0,1.6559,<1H OCEAN,101400.0
4838,-118.28,34.03,45.0,943.0,289.0,953.0,238.0,2.0673,<1H OCEAN,151600.0
...,...,...,...,...,...,...,...,...,...,...
19529,-120.98,37.65,40.0,422.0,63.0,158.0,63.0,7.3841,INLAND,172200.0
12811,-121.52,38.65,17.0,1269.0,233.0,494.0,231.0,3.9615,INLAND,331300.0
2997,-119.03,35.32,12.0,2721.0,549.0,1294.0,523.0,2.5575,INLAND,100200.0
4024,-118.52,34.18,42.0,1611.0,410.0,879.0,386.0,3.1923,<1H OCEAN,221800.0
833,-122.02,37.60,32.0,1295.0,280.0,1156.0,300.0,3.5000,NEAR BAY,154300.0

In [8]:
test_set

,longitud,latitud,antiguedad,habitaciones,dormitorios,población,hogares,ingresos,proximidad,precio
5603,-118.28,33.79,36.0,1989.0,458.0,1668.0,455.0,3.3009,<1H OCEAN,168000.0
12887,-121.34,38.66,18.0,4164.0,963.0,2032.0,898.0,2.1190,INLAND,133100.0
6795,-118.14,34.08,24.0,3988.0,1098.0,2909.0,1034.0,2.7036,<1H OCEAN,170000.0
6460,-118.05,34.10,36.0,1606.0,318.0,889.0,294.0,4.7931,INLAND,272600.0
581,-122.07,37.72,26.0,3204.0,477.0,1411.0,484.0,5.4834,NEAR BAY,295200.0
...,...,...,...,...,...,...,...,...,...,...
14986,-117.03,32.73,34.0,2061.0,NaN,1169.0,400.0,3.5096,NEAR OCEAN,142000.0
11942,-117.42,33.94,35.0,1764.0,325.0,1094.0,353.0,4.1528,INLAND,113900.0
1085,-121.83,39.73,52.0,1741.0,401.0,753.0,377.0,2.0064,INLAND,77900.0
1845,-122.28,37.90,49.0,3191.0,516.0,1148.0,507.0,6.3538,NEAR BAY,333700.0
6404,-118.03,34.14,31.0,4353.0,1117.0,2338.0,1037.0,3.0727,INLAND,242600.0

## Inferencias de la lectura de las anteriores representaciones tabulares 

* 
* 
* 
*

In [9]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16512 entries, 2975 to 833
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   longitud      16512 non-null  float64
 1   latitud       16512 non-null  float64
 2   antiguedad    16512 non-null  float64
 3   habitaciones  16512 non-null  float64
 4   dormitorios   16352 non-null  float64
 5   población     16512 non-null  float64
 6   hogares       16512 non-null  float64
 7   ingresos      16512 non-null  float64
 8   proximidad    16512 non-null  object
 9   precio        16512 non-null  float64
dtypes: float64(9), object(1)
memory usage: 1.4+ MB

## Inferencias

In [10]:
train_set.describe()

,longitud,latitud,antiguedad,habitaciones,dormitorios,población,hogares,ingresos,precio
count,16512.000000,16512.000000,16512.000000,16512.000000,16352.000000,16512.000000,16512.000000,16512.000000,16512.000000
mean,-119.568927,35.629274,28.635174,2628.002422,537.509295,1424.802326,498.672905,3.865530,206689.369307
std,2.002376,2.134855,12.585210,2172.316967,420.795991,1138.160468,380.058029,1.887066,115421.973130
min,-124.350000,32.540000,1.000000,2.000000,2.000000,3.000000,2.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1448.750000,296.000000,787.000000,279.000000,2.562500,119400.000000
50%,-118.490000,34.250000,29.000000,2123.000000,435.000000,1168.000000,410.000000,3.531300,179500.000000
75%,-118.010000,37.710000,37.000000,3138.000000,647.000000,1724.250000,605.000000,4.750000,264625.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [11]:
from sklearn.model_selection import train_test_split

# Dividimos los datos en entrenamiento y prueba
X_train, X_test = train_test_split(v, test_size=0.2)

In [ ]:
X_train

,longitud,latitud,antiguedad,habitaciones,dormitorios,población,hogares,ingresos,proximidad,precio
7562,-118.19,33.90,32.0,2762.0,652.0,2677.0,632.0,2.5719,<1H OCEAN,105600.0
10897,-117.84,33.73,20.0,2572.0,732.0,1534.0,669.0,2.4211,<1H OCEAN,175000.0
16814,-122.43,37.64,34.0,8400.0,1812.0,4101.0,1717.0,4.1033,NEAR OCEAN,301000.0
19822,-119.48,36.44,22.0,1389.0,290.0,1185.0,271.0,2.0857,INLAND,49200.0
10674,-117.86,33.63,17.0,3095.0,551.0,1175.0,534.0,5.3099,<1H OCEAN,500001.0
...,...,...,...,...,...,...,...,...,...,...
20335,-118.94,34.24,5.0,10018.0,1233.0,4253.0,1120.0,8.9063,<1H OCEAN,500001.0
13392,-117.57,34.07,4.0,2152.0,580.0,1083.0,441.0,3.1458,INLAND,118800.0
3444,-118.41,34.25,33.0,827.0,192.0,981.0,184.0,2.6429,<1H OCEAN,143100.0
4449,-118.21,34.07,31.0,1453.0,404.0,1486.0,389.0,2.3859,<1H OCEAN,153100.0
7202,-118.18,34.02,37.0,2631.0,734.0,3228.0,701.0,2.1500,<1H OCEAN,132200.0

In [ ]:
marco

In [ ]:
julio

sklearn
scikitlearn

# Titulo
## Subtitulo
### Titulo de tercer nivel

In [15]:
type("marco")

str

In [19]:
nombre = "marco" 
edad = 47
estatura = 1.65